// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI_caDwD_ii2fmNNNfB8EuMOU9Jcf7Mdk',
    appId: '1:206788565870:web:ddbeb02831ed3f14a7ff7f',
    messagingSenderId: '206788565870',
    projectId: 'my-shop-net2',
    authDomain: 'my-shop-net2.firebaseapp.com',
    storageBucket: 'my-shop-net2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6X8pqcR2WB9tYwkf-ItzOkrWGZIrChYs',
    appId: '1:206788565870:android:88bdc20254825558a7ff7f',
    messagingSenderId: '206788565870',
    projectId: 'my-shop-net2',
    storageBucket: 'my-shop-net2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs9aCskga85mhFNsfTLpiTY6ZB_VKaqU8',
    appId: '1:206788565870:ios:b9be1c5ce3dafc56a7ff7f',
    messagingSenderId: '206788565870',
    projectId: 'my-shop-net2',
    storageBucket: 'my-shop-net2.appspot.com',
    iosClientId: '206788565870-makt2if6kttbvpk1fa7k26r72thjmuou.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs9aCskga85mhFNsfTLpiTY6ZB_VKaqU8',
    appId: '1:206788565870:ios:5b39cc041ed0495aa7ff7f',
    messagingSenderId: '206788565870',
    projectId: 'my-shop-net2',
    storageBucket: 'my-shop-net2.appspot.com',
    iosClientId: '206788565870-o6mtld9aivumm7imjs4hv5kjq0rfvpk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopnet.RunnerTests',
  );
}
